import { format, parseISO } from "date-fns";

export default function DocumentPreview({ record, customer, photos, user, template }) {
  const date = format(parseISO(record.visit_date), "d MMMM yyyy");
  const bizName = user?.business_name || "ServiceProof";
  const engineerName = user?.full_name || "Your Engineer";

  const templateTitles = {
    service_record: "Service Record",
    work_summary: "Work Summary",
    follow_up: "Recommended Follow-Up",
    customer_copy: "Customer Copy",
  };

  return (
    <div className="rounded-2xl border border-border overflow-hidden">
      {/* Dark frame */}
      <div className="bg-card p-3 border-b border-border">
        <p className="text-xs text-muted-foreground text-center">{templateTitles[template]} Preview</p>
      </div>
      
      {/* White A4 document */}
      <div className="bg-white text-gray-900 p-6 space-y-4" style={{ minHeight: 400 }}>
        {/* Header */}
        <div className="flex items-start justify-between">
          <div>
            <h2 className="text-lg font-bold text-teal-600">{bizName}</h2>
            <p className="text-xs text-gray-500">{templateTitles[template]}</p>
          </div>
          {user?.logo_url && (
            <img src={user.logo_url} alt="Logo" className="h-10 w-10 rounded-lg object-cover" />
          )}
        </div>

        <hr className="border-gray-200" />

        {/* Details grid */}
        <div className="grid grid-cols-2 gap-3 text-xs">
          <div>
            <p className="text-gray-500 mb-0.5">Customer</p>
            <p className="font-medium">{customer?.full_name || "N/A"}</p>
          </div>
          <div>
            <p className="text-gray-500 mb-0.5">Date of Visit</p>
            <p className="font-medium">{date}</p>
          </div>
          <div>
            <p className="text-gray-500 mb-0.5">Address</p>
            <p className="font-medium">{customer?.address || "N/A"}</p>
          </div>
          <div>
            <p className="text-gray-500 mb-0.5">Service Type</p>
            <p className="font-medium">{record.service_type}</p>
          </div>
          <div>
            <p className="text-gray-500 mb-0.5">Engineer</p>
            <p className="font-medium">{engineerName}</p>
          </div>
          <div>
            <p className="text-gray-500 mb-0.5">Status</p>
            <p className="font-medium capitalize">{record.status?.replace(/_/g, " ")}</p>
          </div>
        </div>

        {/* Content sections */}
        {record.problem_reported && template !== "work_summary" && (
          <DocSection title="Problem Reported" text={record.problem_reported} />
        )}
        {record.findings && template !== "customer_copy" && (
          <DocSection title="Findings" text={record.findings} />
        )}
        {record.work_completed && (
          <DocSection title="Work Completed" text={record.work_completed} />
        )}
        {record.recommendations && (template === "follow_up" || template === "service_record") && (
          <DocSection title="Recommendations" text={record.recommendations} />
        )}
        {record.follow_up_due_date && (
          <div className="bg-amber-50 rounded-lg p-3 text-xs">
            <p className="font-semibold text-amber-700">Follow-up Due</p>
            <p className="text-amber-600">{format(parseISO(record.follow_up_due_date), "d MMMM yyyy")}</p>
          </div>
        )}

        {/* Photos */}
        {photos.length > 0 && (
          <div>
            <p className="text-xs font-semibold text-gray-700 mb-2">Photos</p>
            <div className="grid grid-cols-2 gap-2">
              {photos.map((p) => (
                <div key={p.id}>
                  <img src={p.photo_url} alt={p.photo_type} className="w-full h-24 object-cover rounded-lg" />
                  <p className="text-[10px] text-gray-500 mt-0.5 capitalize">{p.photo_type}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Signatures */}
        {(record.engineer_signature || record.customer_signature) && (
          <div className="grid grid-cols-2 gap-4 pt-2 border-t border-gray-100">
            {record.engineer_signature && (
              <div>
                <p className="text-[10px] text-gray-500 mb-1">Engineer Signature</p>
                <img src={record.engineer_signature} alt="Engineer" className="h-10 bg-gray-50 rounded p-1" />
              </div>
            )}
            {record.customer_signature && (
              <div>
                <p className="text-[10px] text-gray-500 mb-1">Customer Signature</p>
                <img src={record.customer_signature} alt="Customer" className="h-10 bg-gray-50 rounded p-1" />
              </div>
            )}
          </div>
        )}

        {/* Footer */}
        <div className="text-center pt-4 border-t border-gray-100">
          <p className="text-[10px] text-gray-400">Generated by ServiceProof — Professional proof of service</p>
        </div>
      </div>
    </div>
  );
}

function DocSection({ title, text }) {
  return (
    <div>
      <p className="text-xs font-semibold text-gray-700 mb-1">{title}</p>
      <p className="text-xs text-gray-600 whitespace-pre-wrap">{text}</p>
    </div>
  );
}